# Generated by Django 3.1.5 on 2021-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
