# Generated by Django 3.1.5 on 2021-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='fathers_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
